### ISSUE TITLE
Error with loompy.loompy.combine

### ISSUE THREAD

**Issue by mojaveazure** [linnarsson-lab/loompy#38] opened 2018-02-19 22:29 UTC
I'm trying to combine loom files with the latest version of loompy (pulled from GitHub, commit d0bd1bd), but I get the following error. `tissue_looms` is a list of strings; `combined_name` is a string (enforced in the function call), so I don't think I'm passing something wrong to `combine`.

```python
loompy.loompy.combine(
        files=list(map(str, tissue_looms)), # type: List[str]
        output_file=str(combined_name) # type: str
)
WARNING:root:╭── 'batch_scan_layers' is deprecated. Use 'scan' instead
WARNING:root:╰──> at /usr/local/lib/python3.6/dist-packages/loompy-2.0.6-py3.6.egg/loompy/loompy.py, line 377
<class 'bytes'>
Traceback (most recent call last):
  File "./merge_looms.py", line 111, in <module>
    main()
  File "./merge_looms.py", line 105, in main
    output_file=combined_name
  File "/usr/local/lib/python3.6/dist-packages/loompy-2.0.6-py3.6.egg/loompy/loompy.py", line 933, in combine
    ds.add_loom(f, key, batch_size=batch_size)
  File "/usr/local/lib/python3.6/dist-packages/loompy-2.0.6-py3.6.egg/loompy/loompy.py", line 381, in add_loom
    self.add_columns(vals, ca, fill_values=fill_values)
  File "/usr/local/lib/python3.6/dist-packages/loompy-2.0.6-py3.6.egg/loompy/loompy.py", line 328, in add_columns
    self.ca[key] = np.concatenate([self.ca[key], vals])
  File "/usr/local/lib/python3.6/dist-packages/loompy-2.0.6-py3.6.egg/loompy/attribute_manager.py", line 111, in __setitem__
    return self.__setattr__(name, val)
  File "/usr/local/lib/python3.6/dist-packages/loompy-2.0.6-py3.6.egg/loompy/attribute_manager.py", line 129, in __setattr__
    values = loompy.normalize_attr_values(val)
  File "/usr/local/lib/python3.6/dist-packages/loompy-2.0.6-py3.6.egg/loompy/normalize.py", line 72, in normalize_attr_values
    arr = normalize_attr_strings(arr)
  File "/usr/local/lib/python3.6/dist-packages/loompy-2.0.6-py3.6.egg/loompy/normalize.py", line 19, in normalize_attr_strings
    raise ValueError("Arbitrary numpy object arrays not supported (all elements must be string objects).")
ValueError: Arbitrary numpy object arrays not supported (all elements must be string objects).
```

**Comment by slinnarsson** [comment] 2018-02-21 10:49
I think the origin of the error is somewhere in the attributes of the files you are combining. Could it be that you have attributes with the same name but different type? E.g. if one file has attribute `CellID` with integer values, and the other has `CellID` with string values, then loompy will probably fail to combine them.

It's difficult to debug without access to the input files. If you are willing to share your inputs (for the sole purpose of debugging) I can give it a try. In that case, please send links through email, not here.

Could you run this, and show the result:

```python
for tissue in tissue_looms:
    with loompy.connect(tissue) as ds:
        for attr in ds.ca.keys():
            print(attr, ds.ca[attr].dtype)
```

Btw, if `tissue_looms` is already a list of strings, you don't need to map `str` onto it (same for `combined_name`).

**Comment by mojaveazure** [comment] 2018-02-22 01:23
They're all the same type, but I'm not sure what this object dtype is. I've emailed you a link to the data.

```
Working with 12 groups of loom files
Working on group Trachea (1 of 12)
cell_names object
gene_names object
cell_names object
gene_names object
Working on group Marrow (2 of 12)
cell_names object
gene_names object
cell_names object
gene_names object
Working on group Spleen (3 of 12)
cell_names object
gene_names object
cell_names object
gene_names object
Working on group Heart (4 of 12)
cell_names object
gene_names object
Working on group Lung (5 of 12)
cell_names object
gene_names object
cell_names object
gene_names object
cell_names object
gene_names object
cell_names object
gene_names object
Working on group Liver (6 of 12)
cell_names object
gene_names object
cell_names object
gene_names object
cell_names object
gene_names object
Working on group Kidney (7 of 12)
cell_names object
gene_names object
cell_names object
gene_names object
cell_names object
gene_names object
Working on group Mammary (8 of 12)
cell_names object
gene_names object
cell_names object
gene_names object
Working on group Bladder (9 of 12)
cell_names object
gene_names object
cell_names object
gene_names object
cell_names object
gene_names object
Working on group Tongue (10 of 12)
cell_names object
gene_names object
cell_names object
gene_names object
cell_names object
gene_names object
Working on group Muscle (11 of 12)
cell_names object
gene_names object
cell_names object
gene_names object
Working on group Thymus (12 of 12)
cell_names object
gene_names object
```

**Comment by slinnarsson** [comment] 2018-02-22 15:07
Thanks. I checked your files and it seems that the attributes `cell_names` and `gene_names` are stored as arrays of Python objects, where the objects themselves are byte arrays. For example:

```python
>>> with loompy.connect("Bladder-10X_P4_3.loom") as ds:
>>>    print(ds.ca.cell_names[0])

b'AAAGTAGAGATGCCAG'
```

Note the `b` in front, indicating that these are not strings but arrays of bytes. This was probably caused by some weird typecasting when you created the file. If you like, I can check your code if you post it here, to make sure there's not a bug in loom when given some particular input.

Here's code that works for me. First, create a loom file for each of the [tabula muris](https://figshare.com/articles/Single-cell_RNA-seq_data_from_microfluidic_emulsion/5715025) samples (change the `root` to wherever you have put the downloaded unzipped archive):

```python
import loompy
import os
import numpy as np
from scipy.io import mmread

root = "/Users/sten/Downloads/5715025/droplet/"
for fname in os.listdir(root):
    if "10X" in fname:
        with open(os.path.join(root, fname, "genes.tsv"), "r") as f:
            gene = np.array([x.split("\t")[1].strip() for x in f.readlines()])
        with open(os.path.join(root, fname, "barcodes.tsv"), "r") as f:
            cellids = np.array([x.strip() for x in f.readlines()])
        col_attrs = {"CellID": cellids, "Sample": [fname] * cellids.shape[0]}
        row_attrs = {"Gene": gene}

        matrix = mmread(os.path.join(root, fname, "matrix.mtx"))
        loompy.create(os.path.join(root, fname, fname + ".loom"), matrix, row_attrs, col_attrs)
```

Note that `mmread` returns a `scipy.coo_matrix` (a sparse matrix) and `loompy.create` writes this to the loom file without making it dense. 

Next, combine the bladder files:

```python
files = [os.path.join(root, x) for x in ["Bladder-10X_P4_3.loom", "Bladder-10X_P4_4.loom", "Bladder-10X_P4_4.loom"]]
loompy.combine(files, "Bladder.loom")
```

This works and creates a pooled file. You may want to pool all the samples together. In the code above, I added a column attribute `Sample` which you can use to keep track of where each cell came from originally.

Hope this helps, and let me know if it doesn't!

**Comment by mojaveazure** [comment] 2018-02-26 20:13
I'm wondering if there's some incompatibility between R's and Python's HDF5 implementations then. I used Seurat's [Read10X](https://github.com/satijalab/seurat/blob/master/R/preprocessing.R#L174) function, which returns a sparse matrix with cell IDs as colnames and gene names are rownames, and loomR's [create](https://github.com/mojaveazure/loomR/blob/develop/R/loom.R#L1015) function to make the individual loom files.
```R
library(loomR)
library(Seurat)

root.dir <- '/home/paul/tabula_muris/droplet'
loom.dir <- file.path(dirname(path = root.dir), 'looms')
if (!dir.exists(paths = loom.dir)) {
  dir.create(path = loom.dir, showWarnings = FALSE, recursive = TRUE)
}
data.dir <- list.dirs(path = root.dir)
data.dir <- data.dir[which(x = data.dir != root.dir)]

for (dir in data.dir) {
  cat('\n', "Working on", basename(path = dir), '\n')
  name <- basename(path = dir)
  expr <- Read10X(data.dir = dir)
  lfile <- create(
    filename = file.path(loom.dir, paste0(name, '.loom')),
    data = t(x = expr),
    overwrite = TRUE
  )
  lfile$close_all()
  gc(verbose = FALSE)
}
```

Off the top of your head, do you know if there's something I should be doing to strings in R to get them read properly as strings in Python? When R reconnects to the loom files, it reads the row and column attributes as [HDF5 Strings](https://hhoeflin.github.io/hdf5r/reference/H5T_STRING-class.html), but I'm wondering if there's some underlying incompatibility I'm not thinking about.
```R
> library(hdf5r)
> loom.dir <- '~/tabula_muris/looms/'
> loom.files <- list.files(path = loom.dir, pattern = 'loom', full.names = TRUE)
> row.types <- c()
> col.types <- c()
> mat.types <- c()
> lay.types <- c()
> for (l in loom.files) {
+   hfile <- h5file(filename = l, mode = 'r')
+   ds <- list.datasets(object = hfile, recursive = TRUE)
+   for (d in ds) {
+     dtype <- as.character(x = hfile[[d]]$get_type()$get_class())
+     if (d == 'matrix') {
+       mat.types <- c(mat.types, dtype)
+     } else if (dirname(path = d) == 'col_attrs') {
+       col.types <- c(col.types, dtype)
+     } else if (dirname(path = d) == 'row_attrs') {
+       row.types <- c(row.types, dtype)
+     } else if (dirname(path = d) == 'layers') {
+       lay.types <- c(lay.types, dtype)
+     }
+   }
+   hfile$close_all()
+ }
> unique(x = row.types)
[1] "H5T_STRING"
> unique(x = col.types)
[1] "H5T_STRING"
> unique(x = mat.types)
[1] "H5T_FLOAT"
> unique(x = lay.types)
NULL
```

**Comment by sejiro** [comment] 2018-03-01 22:44
Hello,

I am having an issue using combine as well. 
I have generated two loom files which I have checked individually the ratios of spliced, unspliced and ambiguous reads. However when I go to combine these files I get an error that 'layerambiguous' does not exist.
![screen shot 2018-03-01 at 5 33 17 pm](https://user-images.githubusercontent.com/10656316/36873648-1646cfbe-1d77-11e8-98f2-0ab44a85bd92.png)
I think this is for the second file as when I first made the file I didnt change the row limit and when I try to plot these ratios I get a boolean index index array mismatch error. Some help understanding what is going on under the hood with these calls and what I am misunderstanding would be most appreciated. 
![screen shot 2018-03-01 at 5 41 52 pm](https://user-images.githubusercontent.com/10656316/36873871-e2490352-1d77-11e8-9204-e27650b3315e.png)

**Comment by sejiro** [comment] 2018-03-01 22:51
is the problem something like it is looking for "layersambiguous" when it only needs to look for layer "ambbiguous"?

**Comment by slinnarsson** [comment] 2018-03-02 16:16
Hi

I think if you update using ”pip install -U loompy” and make sure you’re on 2.0.7 or newer, it will work!

**Comment by sejiro** [comment] 2018-03-02 16:24
I have just updated the package on our cluster and my initial checks indicate this newer version of loompy does indeed solve my problem. Thank you for the follow up! Really like the work between all of your labs, been working a lot with seurat and velocyto recently. 

best,
-Sejiro

**Comment by slinnarsson** [comment] 2018-03-20 08:03
Great, good to know!

**Closed by slinnarsson** 2018-03-20 08:03 UTC
